PROGRAM TEST14_FORTRAN
    USE MPI
    USE PAPYRUS
    IMPLICIT NONE
    
    INTEGER :: RANK, NRANKS, IERROR, PROVIDED, PEER, DB
    CHARACTER, DIMENSION(0:3) :: KEY * 32
    CHARACTER, DIMENSION(0:3) :: VAL * 256
    CHARACTER, POINTER :: VAL1(:)
    CHARACTER, POINTER :: VAL2(:)
    INTEGER(KIND=8) :: KEYLEN, VALLEN

    CALL MPI_INIT_THREAD(MPI_THREAD_MULTIPLE, PROVIDED, IERROR)
    CALL PAPYRUSKV_INIT('./pkv_repo'//CHAR(0), IERROR)
    IF (IERROR /= PAPYRUSKV_OK) THEN
        PRINT*, 'FAILED'
    ENDIF

    CALL MPI_COMM_RANK(MPI_COMM_WORLD, RANK, IERROR)
    CALL MPI_COMM_SIZE(MPI_COMM_WORLD, NRANKS, IERROR)

    KEY(0) = 'GOOGLE'
    KEY(1) = 'FACEBOOK'
    KEY(2) = 'TWITTER'
    KEY(3) = 'PAPYRUS'

    VAL(0) = 'https://google.com'
    VAL(1) = 'https://facebook.com'
    VAL(2) = 'https://twitter.com'
    VAL(3) = 'https://code.ornl.gov/eck/papyrus'

    ALLOCATE(VAL1(256))
    NULLIFY(VAL2)

    IF (RANK == NRANKS - 1) THEN
        PEER = 0
    ELSE
        PEER = RANK + 1
    ENDIF

    CALL PAPYRUSKV_OPEN('TEST_DB'//CHAR(0), IOR(PAPYRUSKV_CREATE, PAPYRUSKV_RDWR), DB, IERROR)
    IF (IERROR /= PAPYRUSKV_OK) THEN
        PRINT*, 'FAILED'
    ENDIF

    IF (RANK < SIZE(KEY)) THEN
        PRINT*, 'PUT--> RANK', RANK, 'KEY:', TRIM(KEY(RANK)), ' VAL:', TRIM(VAL(RANK))
        KEYLEN = LEN(TRIM(KEY(RANK)), KIND = 8)
        VALLEN = LEN(TRIM(VAL(RANK)), KIND = 8)
        CALL PAPYRUSKV_PUT(DB, TRIM(KEY(RANK)), KEYLEN, TRIM(VAL(RANK)), VALLEN, IERROR)
        IF (IERROR /= PAPYRUSKV_OK) THEN
            PRINT*, 'FAILED'
        ENDIF
    END IF

    CALL PAPYRUSKV_BARRIER(DB, PAPYRUSKV_MEMTABLE, IERROR)
    IF (IERROR /= PAPYRUSKV_OK) THEN
        PRINT*, 'FAILED'
    ENDIF

    IF (RANK < SIZE(KEY)) THEN
        CALL PAPYRUSKV_GET(DB, TRIM(KEY(RANK)), KEYLEN, VAL1, VALLEN, IERROR)
        IF (IERROR /= PAPYRUSKV_OK) THEN
            PRINT*, 'FAILED'
        ENDIF
        PRINT*, 'GET--> RANK', RANK, 'KEY:', TRIM(KEY(RANK)), ' VAL:', VAL1(1: VALLEN)

        CALL PAPYRUSKV_GET(DB, TRIM(KEY(RANK)), KEYLEN, VAL2, VALLEN, IERROR)
        IF (IERROR /= PAPYRUSKV_OK) THEN
            PRINT*, 'FAILED'
        ENDIF
        PRINT*, 'GET--> RANK', RANK, 'KEY:', TRIM(KEY(RANK)), ' VAL:', VAL2(1: VALLEN)
        CALL PAPYRUSKV_FREE(VAL2, IERROR)
        IF (IERROR /= PAPYRUSKV_OK) THEN
            PRINT*, 'FAILED'
        ENDIF

        KEYLEN = LEN(TRIM(KEY(PEER)), KIND = 8)
        CALL PAPYRUSKV_GET(DB, TRIM(KEY(PEER)), KEYLEN, VAL1, VALLEN, IERROR)
        IF (IERROR /= PAPYRUSKV_OK) THEN
            PRINT*, 'FAILED'
        ENDIF
        PRINT*, 'GET--> RANK', RANK, 'KEY:', TRIM(KEY(PEER)), ' VAL:', VAL1(1: VALLEN)
        
        KEYLEN = LEN(TRIM(KEY(PEER)), KIND = 8)
        CALL PAPYRUSKV_GET(DB, TRIM(KEY(PEER)), KEYLEN, VAL2, VALLEN, IERROR)
        IF (IERROR /= PAPYRUSKV_OK) THEN
            PRINT*, 'FAILED'
        ENDIF
        PRINT*, 'GET--> RANK', RANK, 'KEY:', TRIM(KEY(PEER)), ' VAL:', VAL2(1: VALLEN)
        CALL PAPYRUSKV_FREE(VAL2, IERROR)
        IF (IERROR /= PAPYRUSKV_OK) THEN
            PRINT*, 'FAILED'
        ENDIF
    END IF

    CALL PAPYRUSKV_CLOSE(DB, IERROR)
    IF (IERROR /= PAPYRUSKV_OK) THEN
        PRINT*, 'FAILED'
    ENDIF

    DEALLOCATE(VAL1)

    CALL PAPYRUSKV_FINALIZE(IERROR)
    IF (IERROR /= PAPYRUSKV_OK) THEN
        PRINT*, 'FAILED'
    ENDIF
    CALL MPI_FINALIZE(IERROR)
END PROGRAM TEST14_FORTRAN
